title: Hacker-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "NullDoot2k"
  email: "nulldoot2k@proton.me"
  url: ""

baseurl: /
urls:
  - text: Home
    url: /
  - text: Hidden
    url: /hidden

source: .
destination: ./_site
# permalink: /:title
permalink: pretty
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NullDoot2k"
year : "2022"

markdown: kramdown
kramdown:
  parse_block_html: true
  # parse_span_html: true

highlighter: rouge
input: GFM
